from __future__ import annotations

import zipfile
from email.message import EmailMessage
from pathlib import Path

import fitz
from docx import Document as DocxDocument
from openpyxl import Workbook
from PIL import Image, ImageDraw
from pptx import Presentation


def write_text(path: Path, content: str, encoding: str = "utf-8") -> Path:
    path.write_text(content, encoding=encoding)
    return path


def write_bytes(path: Path, data: bytes) -> Path:
    path.write_bytes(data)
    return path


def make_docx(path: Path) -> Path:
    doc = DocxDocument()
    doc.add_heading("Quarterly Review", level=1)
    doc.add_paragraph("The contract remains effective.")
    table = doc.add_table(rows=2, cols=2)
    table.cell(0, 0).text = "Item"
    table.cell(0, 1).text = "Amount"
    table.cell(1, 0).text = "License"
    table.cell(1, 1).text = "1200"
    doc.save(path)
    return path


def make_pptx(path: Path) -> Path:
    prs = Presentation()
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Launch Plan"
    slide.placeholders[1].text = "Ship the parser in phase one."
    notes = slide.notes_slide.notes_text_frame
    notes.text = "Remember to mention OCR routing."
    prs.save(path)
    return path


def make_xlsx(path: Path) -> Path:
    wb = Workbook()
    ws = wb.active
    ws.title = "Sales"
    ws["A1"] = "Q1 Report"
    ws["A2"] = "generated by finance"
    ws["A4"] = "Region"
    ws["B4"] = "Product"
    ws["C4"] = "Units"
    ws.merge_cells("A5:A6")
    ws["A5"] = "North"
    ws["B5"] = "Widget"
    ws["C5"] = 120
    ws["B6"] = "Gadget"
    ws["C6"] = 80
    wb.save(path)
    return path


def make_digital_pdf(path: Path) -> Path:
    doc = fitz.open()
    page = doc.new_page()
    page.insert_text((72, 72), "Digital Title", fontsize=22)
    page.insert_text((72, 120), "This paragraph is a native PDF text layer.", fontsize=11)
    doc.save(path)
    doc.close()
    return path


def make_scanned_pdf(path: Path) -> Path:
    image = Image.new("RGB", (600, 800), "white")
    draw = ImageDraw.Draw(image)
    draw.text((40, 60), "Scanned invoice", fill="black")
    image_path = path.with_suffix(".png")
    image.save(image_path)
    doc = fitz.open()
    page = doc.new_page(width=600, height=800)
    page.insert_image(page.rect, filename=str(image_path))
    doc.save(path)
    doc.close()
    return path


def make_html(path: Path) -> Path:
    path.write_text(
        """<!doctype html>
<html>
<head><title>Portal</title>
<script>alert('x')</script>
</head>
<body>
<nav>Home About</nav>
<article>
<h1>Main Story</h1>
<p>Visible paragraph.</p>
<table><tr><th>A</th><th>B</th></tr><tr><td>1</td><td>2</td></tr></table>
</article>
<footer>unsubscribe</footer>
</body></html>
""",
        encoding="utf-8",
    )
    return path


def make_eml_with_attachment(path: Path, attachment: Path) -> Path:
    message = EmailMessage()
    message["From"] = "a@example.com"
    message["To"] = "b@example.com"
    message["Subject"] = "Please review"
    message.set_content("See the attached note.")
    message.add_attachment(
        attachment.read_bytes(),
        maintype="text",
        subtype="plain",
        filename=attachment.name,
    )
    path.write_bytes(message.as_bytes())
    return path


def make_zip(path: Path, files: dict[str, Path]) -> Path:
    with zipfile.ZipFile(path, "w") as archive:
        for name, file_path in files.items():
            archive.write(file_path, arcname=name)
    return path
